### ISSUE TITLE
load method reads at wrong offset

### ISSUE THREAD

**Issue by seeliger-ec** [baderouaich/BitmapPlusPlus#1]
Reading 24bit Bitmaps saved by gimp via load(...) resulted in corrupted image data.
I was able to fix this in the given scenario by adding
ifs.seekg(header->offset_bits);
after reading the header and before reading the image data. (around line 519 of BitmapPlusPlus.hpp)

**Comment by baderouaich** [comment]
Hi @seeliger-ec , Thank you for opening this issue!

You are right, I tried to load a 24bpp bitmap saved with gimp and it was not loading correctly. 

As you mentioned, pixels reading & writing should always start from `header->offset_bits` which was not the case.
I guess I just assumed that after std::ifstream reads/writes BitmapHeader, the offset will point automatically at the beginning of pixels data but that is not always the case, gimp seems to put add extra information between the end of the header and the starting offset of pixels data as displayed below (the yellow area):

![image](https://github.com/user-attachments/assets/b0b55867-81f9-42e7-9db1-c246ef03b8ed)

I have fixed this by adding your suggestion `ifs.seekg(header->offset_bits);` in the load function.
Thank you again and have a nice day.
Bader
