### ISSUE TITLE
Compilation errors in Visual Studio 2022

### ISSUE THREAD

**Issue by Adrian104** [baderouaich/BitmapPlusPlus#2]
Hello!

First of all, thank you for developing this great library!
The issue is that Visual Studio (version 17.10.6 to be exact) will throw errors whenever I try to compile some code that uses BitmapPlusPlus:
![image](https://github.com/user-attachments/assets/ee092035-d271-4a0b-889a-e1b4514d7d23)

After searching for a while, it looks like that there are two problems:

1. For some reason, VS doesn’t natively support alternative tokens like `not` or `and`, despite the fact that they are technically defined by the C++ standard. I found out at least three different solutions:
    1. Flag `/permissive-` could be used to force the compiler to be standard compliant (can be done with CMake).
    2. Tokens `and` and `not` could be replaced with `&&` and `!`.
    3. Adding `#include <iso646.h>` also fixes this problem.

2. Visual Studio 2022 still defaults to C++14, but structured bindings require C++17 (quick fix in CMake).

Of course the issue is specific to VS. Other compilers like GCC or Clang compile without any issues (tested on Linux with glibc). Still, I think that for those who use VS it will be a good idea to fix those problems, so I will open a PR.

**Comment by baderouaich** [comment]
Hello! First of all, thank you for your interest in this library.
Indeed MSVC does not support alternative tokens prior to C++17. I never had the opportunity to test the library in Windows. Perhaps I should setup some CI builds in multiple platforms with multiple compilers.
I appreciate the time you took to investigate and solve the issue! I will review the PR #3 asap.
Thanks again and have a great day!
